# Aula 01

## Importando a biblioteca Pandas

In [2]:
import pandas as pd

## Lendo o **Dataset** sobre o faturamento de vinhos

In [3]:
vinhos = pd.read_csv('/content/drive/MyDrive/2022/Data Science/faturamento_quinzena_nov2021.csv', sep=';')

## Conhecendo o **dataset**

In [4]:
# Saber quantas linhas e colunas meu dataframe tem
vinhos.shape

(45, 5)

In [6]:
# Listar as colunas do dataframe
vinhos.columns

Index(['data', 'estilo', 'quantidade de garrafas', 'preço da garrafa',
       'total'],
      dtype='object')

In [7]:
# Conhecer os tipos de dados do meu dataframe
vinhos.dtypes

data                       object
estilo                     object
quantidade de garrafas      int64
preço da garrafa          float64
total                     float64
dtype: object

In [8]:
# Pegando mais informações
vinhos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   data                    45 non-null     object
 1   estilo                  45 non-null     object
 2   quantidade de garrafas  45 non-null     int64
 3   preço da garrafa        45 non-null     float64
 4   total                   45 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 1.9+ KB

In [9]:
# Pegando uma maior detalhamento com o método describe()
vinhos.describe()

       quantidade de garrafas  preço da garrafa        total
count               45.000000         45.000000    45.000000
mean                 8.244444        100.296667   863.980667
std                  4.156898         35.544601   614.730403
min                  1.000000         75.000000    75.890000
25%                  5.000000         75.000000   379.450000
50%                  8.000000         75.890000   758.900000
75%                 10.000000        150.000000  1050.000000
max                 20.000000        150.000000  3000.000000

In [5]:
# Recupero as 5 primeiras linhas do dataframe
vinhos.head()

         data     estilo  quantidade de garrafas  preço da garrafa    total
0  2021-11-01      tinto                       7            150.00  1050.00
1  2021-11-01     branco                       4             75.00   300.00
2  2021-11-01  espumante                       5             75.89   379.45
3  2021-11-02      tinto                       3            150.00   450.00
4  2021-11-02     branco                       2             75.00   150.00

## Explorando o **dataframe**

In [10]:
# Pegando os valores únicos da coluna estilo
vinhos['estilo'].unique()

array(['tinto', 'branco', 'espumante'], dtype=object)

In [11]:
# Selecionando 3 colunas do dataframe e fazendo um slide
# para retornar 3 linhas
vinhos[['data', 'estilo', 'preço da garrafa']][1:4]

         data     estilo  preço da garrafa
1  2021-11-01     branco             75.00
2  2021-11-01  espumante             75.89
3  2021-11-02      tinto            150.00

In [12]:
# Retornando o tipo de dado
estilo = vinhos['estilo']
type(estilo)

pandas.core.series.Series

## Criando um dataframe

In [13]:
pd.DataFrame({
    'Yes': [50, 21],
    'No': [10, 15]
})

   Yes  No
0   50  10
1   21  15

In [14]:
pd.DataFrame({
    'Professores': ['Rafael', 'Xavier', 'Pascoal', 'Murilo'],
    'e-Mail': ['rafael@email.com', 'xavier@email.com', 'pascoal@email.com', 'murilo@email.com']
})

  Professores             e-Mail
0      Rafael   rafael@email.com
1      Xavier   xavier@email.com
2     Pascoal  pascoal@email.com
3      Murilo   murilo@email.com